/**
 * HiveMind Template Library
 * Pre-built brainstorm templates for common use cases
 */

export interface TemplateNode {
  q: number;
  r: number;
  text: string;
  description: string;
  type: "concept" | "action" | "technical" | "question" | "risk";
  isPinned?: boolean;
  depth: number;
}

export interface Template {
  id: string;
  name: string;
  description: string;
  category: "product" | "creative" | "business" | "problem-solving" | "research";
  icon: string;
  nodes: TemplateNode[];
  centerText: string;
}

export const TEMPLATES: Template[] = [
  {
    id: "product-launch",
    name: "Product Launch Planning",
    description: "Comprehensive framework for planning a new product launch",
    category: "product",
    icon: "🚀",
    centerText: "Product Launch",
    nodes: [
      // Center node
      {
        q: 0,
        r: 0,
        text: "Product Launch",
        description: "Central planning hub for product launch strategy",
        type: "concept",
        isPinned: true,
        depth: 0,
      },
      // First ring - 6 main areas
      {
        q: 1,
        r: 0,
        text: "Market Research",
        description: "Target audience analysis and competitive landscape",
        type: "concept",
        depth: 1,
      },
      {
        q: 1,
        r: -1,
        text: "Product Features",
        description: "Core functionality and unique value propositions",
        type: "technical",
        depth: 1,
      },
      {
        q: 0,
        r: -1,
        text: "Marketing Strategy",
        description: "Channels, messaging, and campaign planning",
        type: "action",
        depth: 1,
      },
      {
        q: -1,
        r: 0,
        text: "Launch Timeline",
        description: "Milestones, deadlines, and critical path",
        type: "action",
        depth: 1,
      },
      {
        q: -1,
        r: 1,
        text: "Budget & Resources",
        description: "Financial planning and team allocation",
        type: "technical",
        depth: 1,
      },
      {
        q: 0,
        r: 1,
        text: "Risk Mitigation",
        description: "Potential obstacles and contingency plans",
        type: "risk",
        depth: 1,
      },
    ],
  },
  {
    id: "novel-writing",
    name: "Novel Writing",
    description: "Story development framework for fiction writers",
    category: "creative",
    icon: "📖",
    centerText: "Novel Concept",
    nodes: [
      {
        q: 0,
        r: 0,
        text: "Novel Concept",
        description: "Central story idea and premise",
        type: "concept",
        isPinned: true,
        depth: 0,
      },
      {
        q: 1,
        r: 0,
        text: "Main Characters",
        description: "Protagonist, antagonist, and supporting cast",
        type: "concept",
        depth: 1,
      },
      {
        q: 1,
        r: -1,
        text: "Plot Structure",
        description: "Three-act structure, key turning points, climax",
        type: "action",
        depth: 1,
      },
      {
        q: 0,
        r: -1,
        text: "World Building",
        description: "Setting, rules, culture, and atmosphere",
        type: "concept",
        depth: 1,
      },
      {
        q: -1,
        r: 0,
        text: "Themes & Motifs",
        description: "Central messages and recurring symbols",
        type: "concept",
        depth: 1,
      },
      {
        q: -1,
        r: 1,
        text: "Conflict & Stakes",
        description: "What's at risk? Internal and external conflicts",
        type: "question",
        depth: 1,
      },
      {
        q: 0,
        r: 1,
        text: "Narrative Voice",
        description: "POV, tone, and storytelling style",
        type: "technical",
        depth: 1,
      },
    ],
  },
  {
    id: "problem-solving",
    name: "Problem Solving Framework",
    description: "Systematic approach to analyzing and solving complex problems",
    category: "problem-solving",
    icon: "🧩",
    centerText: "Problem Statement",
    nodes: [
      {
        q: 0,
        r: 0,
        text: "Problem Statement",
        description: "Clear definition of the problem to solve",
        type: "concept",
        isPinned: true,
        depth: 0,
      },
      {
        q: 1,
        r: 0,
        text: "Root Causes",
        description: "Underlying factors contributing to the problem",
        type: "question",
        depth: 1,
      },
      {
        q: 1,
        r: -1,
        text: "Potential Solutions",
        description: "Brainstorm multiple approaches and alternatives",
        type: "action",
        depth: 1,
      },
      {
        q: 0,
        r: -1,
        text: "Success Criteria",
        description: "How will we measure if the problem is solved?",
        type: "question",
        depth: 1,
      },
      {
        q: -1,
        r: 0,
        text: "Implementation Plan",
        description: "Step-by-step action plan and timeline",
        type: "action",
        depth: 1,
      },
      {
        q: -1,
        r: 1,
        text: "Constraints & Risks",
        description: "Limitations, obstacles, and potential failures",
        type: "risk",
        depth: 1,
      },
      {
        q: 0,
        r: 1,
        text: "Stakeholders",
        description: "Who is affected? Who needs to be involved?",
        type: "concept",
        depth: 1,
      },
    ],
  },
  {
    id: "business-strategy",
    name: "Business Strategy",
    description: "Strategic planning framework for business growth",
    category: "business",
    icon: "💼",
    centerText: "Business Vision",
    nodes: [
      {
        q: 0,
        r: 0,
        text: "Business Vision",
        description: "Long-term goals and company mission",
        type: "concept",
        isPinned: true,
        depth: 0,
      },
      {
        q: 1,
        r: 0,
        text: "Market Positioning",
        description: "Competitive advantage and differentiation",
        type: "concept",
        depth: 1,
      },
      {
        q: 1,
        r: -1,
        text: "Revenue Streams",
        description: "How will the business make money?",
        type: "technical",
        depth: 1,
      },
      {
        q: 0,
        r: -1,
        text: "Growth Strategy",
        description: "Expansion plans and scaling approach",
        type: "action",
        depth: 1,
      },
      {
        q: -1,
        r: 0,
        text: "Key Partnerships",
        description: "Strategic alliances and collaboration opportunities",
        type: "concept",
        depth: 1,
      },
      {
        q: -1,
        r: 1,
        text: "Market Threats",
        description: "Competition, disruption, and market risks",
        type: "risk",
        depth: 1,
      },
      {
        q: 0,
        r: 1,
        text: "Core Competencies",
        description: "What makes us uniquely qualified to succeed?",
        type: "question",
        depth: 1,
      },
    ],
  },
  {
    id: "research-project",
    name: "Research Project",
    description: "Academic or scientific research planning framework",
    category: "research",
    icon: "🔬",
    centerText: "Research Question",
    nodes: [
      {
        q: 0,
        r: 0,
        text: "Research Question",
        description: "Central hypothesis or question to investigate",
        type: "question",
        isPinned: true,
        depth: 0,
      },
      {
        q: 1,
        r: 0,
        text: "Literature Review",
        description: "Existing research and theoretical framework",
        type: "concept",
        depth: 1,
      },
      {
        q: 1,
        r: -1,
        text: "Methodology",
        description: "Research design, data collection, and analysis methods",
        type: "technical",
        depth: 1,
      },
      {
        q: 0,
        r: -1,
        text: "Data Sources",
        description: "Where will data come from? Sample size and selection",
        type: "technical",
        depth: 1,
      },
      {
        q: -1,
        r: 0,
        text: "Expected Outcomes",
        description: "Hypotheses and anticipated findings",
        type: "concept",
        depth: 1,
      },
      {
        q: -1,
        r: 1,
        text: "Limitations",
        description: "Constraints, biases, and validity concerns",
        type: "risk",
        depth: 1,
      },
      {
        q: 0,
        r: 1,
        text: "Timeline & Milestones",
        description: "Research phases and completion targets",
        type: "action",
        depth: 1,
      },
    ],
  },
  {
    id: "content-strategy",
    name: "Content Strategy",
    description: "Content marketing and creation planning",
    category: "business",
    icon: "✍️",
    centerText: "Content Strategy",
    nodes: [
      {
        q: 0,
        r: 0,
        text: "Content Strategy",
        description: "Overall content vision and goals",
        type: "concept",
        isPinned: true,
        depth: 0,
      },
      {
        q: 1,
        r: 0,
        text: "Target Audience",
        description: "Who are we creating content for?",
        type: "question",
        depth: 1,
      },
      {
        q: 1,
        r: -1,
        text: "Content Pillars",
        description: "Core themes and topic categories",
        type: "concept",
        depth: 1,
      },
      {
        q: 0,
        r: -1,
        text: "Distribution Channels",
        description: "Where will content be published and promoted?",
        type: "action",
        depth: 1,
      },
      {
        q: -1,
        r: 0,
        text: "Content Calendar",
        description: "Publishing schedule and frequency",
        type: "action",
        depth: 1,
      },
      {
        q: -1,
        r: 1,
        text: "Performance Metrics",
        description: "How will we measure success?",
        type: "technical",
        depth: 1,
      },
      {
        q: 0,
        r: 1,
        text: "Resource Requirements",
        description: "Team, tools, and budget needed",
        type: "technical",
        depth: 1,
      },
    ],
  },
  {
    id: "app-design",
    name: "App Design",
    description: "Mobile or web application design planning",
    category: "product",
    icon: "📱",
    centerText: "App Concept",
    nodes: [
      {
        q: 0,
        r: 0,
        text: "App Concept",
        description: "Core app idea and value proposition",
        type: "concept",
        isPinned: true,
        depth: 0,
      },
      {
        q: 1,
        r: 0,
        text: "User Personas",
        description: "Who will use this app and why?",
        type: "concept",
        depth: 1,
      },
      {
        q: 1,
        r: -1,
        text: "Core Features",
        description: "Essential functionality and user flows",
        type: "technical",
        depth: 1,
      },
      {
        q: 0,
        r: -1,
        text: "UI/UX Design",
        description: "Visual design, navigation, and interaction patterns",
        type: "action",
        depth: 1,
      },
      {
        q: -1,
        r: 0,
        text: "Technical Stack",
        description: "Platform, frameworks, and infrastructure",
        type: "technical",
        depth: 1,
      },
      {
        q: -1,
        r: 1,
        text: "Monetization",
        description: "How will the app generate revenue?",
        type: "question",
        depth: 1,
      },
      {
        q: 0,
        r: 1,
        text: "Launch Strategy",
        description: "Beta testing, marketing, and rollout plan",
        type: "action",
        depth: 1,
      },
    ],
  },
  {
    id: "event-planning",
    name: "Event Planning",
    description: "Comprehensive event organization framework",
    category: "business",
    icon: "🎉",
    centerText: "Event Vision",
    nodes: [
      {
        q: 0,
        r: 0,
        text: "Event Vision",
        description: "Purpose, theme, and desired outcomes",
        type: "concept",
        isPinned: true,
        depth: 0,
      },
      {
        q: 1,
        r: 0,
        text: "Venue & Logistics",
        description: "Location, capacity, setup, and equipment",
        type: "technical",
        depth: 1,
      },
      {
        q: 1,
        r: -1,
        text: "Guest Experience",
        description: "Registration, activities, and engagement",
        type: "action",
        depth: 1,
      },
      {
        q: 0,
        r: -1,
        text: "Marketing & Promotion",
        description: "How will we attract attendees?",
        type: "action",
        depth: 1,
      },
      {
        q: -1,
        r: 0,
        text: "Budget & Sponsorship",
        description: "Costs, funding sources, and financial planning",
        type: "technical",
        depth: 1,
      },
      {
        q: -1,
        r: 1,
        text: "Risk Management",
        description: "Contingency plans, insurance, and safety",
        type: "risk",
        depth: 1,
      },
      {
        q: 0,
        r: 1,
        text: "Timeline & Checklist",
        description: "Pre-event, day-of, and post-event tasks",
        type: "action",
        depth: 1,
      },
    ],
  },
];

export const TEMPLATE_CATEGORIES = [
  { id: "all", name: "All Templates", icon: "🌐" },
  { id: "product", name: "Product & Design", icon: "🚀" },
  { id: "creative", name: "Creative Writing", icon: "📖" },
  { id: "business", name: "Business & Strategy", icon: "💼" },
  { id: "problem-solving", name: "Problem Solving", icon: "🧩" },
  { id: "research", name: "Research & Analysis", icon: "🔬" },
];
